### ISSUE TITLE
OpenCVOptions object does not get applied

### ISSUE THREAD

**Issue by tonivrbic** [devakone/ng-open-cv#6]
While working with this library I've found that the options object does not get applied (the DEFAULT_OPTIONS are always applied).

After some digging, I think the problem is in this line (the provided options object is missing the spread operator):
https://github.com/devakone/ng-open-cv/blob/9c8407713b16dcdc72762db9c4eb184568338570/projects/ng-open-cv/src/lib/ng-open-cv.service.ts#L43
Currently the provided options object is nested inside the default options.

I think the correct solution should be:
```typescript
const opts = { ...this.DEFAULT_OPTIONS, ...options }; 
```

**Comment by devakone** [comment]
Thanks for reporting this @tonivrbic . I'll add a fix for it
